<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EEIP</AssemblyName>
    <RootNamespace>Sres.Networking.Eeip.Library</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <Version>1.6.0</Version>
    <Product>EEIP.NET</Product>
    <Description>Ethernet/IP</Description>
    <Copyright>Copyright © 2018-2020</Copyright>
    <PackageTags>Ethernet/IP EIP EEIP</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EEIP.NET.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="LabView Example\**;Notes\**" />
  </ItemGroup>
</Project>
